#%RAML 1.0 NamedExample
value: 
  -
    name: ACME
    type: business
    address: "1 Main St, Los Angeles, CA, 92000, USA"
    air_miles: 5000
  -
    name: Bob Brow
    type: personal
    address: "1 Main St, Los Angeles, CA, 92000, USA"
    air_miles: 6000